<?php

namespace Brevo\CustomObjects\Types;

use Brevo\Core\Json\JsonSerializableType;
use Brevo\Core\Json\JsonProperty;

/**
 * Identifiers attached with the associated object record. Only includes the internal ID.
 */
class GetrecordsResponseRecordsItemAssociationsItemOneRecordsItemZeroIdentifiers extends JsonSerializableType
{
    /**
     * @var ?int $id Internal ID of the insurance object record generated by Brevo
     */
    #[JsonProperty('id')]
    public ?int $id;

    /**
     * @param array{
     *   id?: ?int,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->id = $values['id'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
