<?php

namespace Brevo\CustomObjects\Types;

use Brevo\Core\Json\JsonSerializableType;
use Brevo\Core\Json\JsonProperty;

/**
 * Identifiers attached with the object record. It can have id or ext_id. ext_id is ID of record in the external system that client want to store in the object system, id is an internal ID of object record generated by Brevo system.
 */
class GetrecordsResponseRecordsItemIdentifiers extends JsonSerializableType
{
    /**
     * @var ?string $extId ext_id is ID of record in the external system that client_dev want to store in the object system.
     */
    #[JsonProperty('ext_id')]
    public ?string $extId;

    /**
     * @var ?int $id Internal ID of the object record generated by Brevo
     */
    #[JsonProperty('id')]
    public ?int $id;

    /**
     * @param array{
     *   extId?: ?string,
     *   id?: ?int,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->extId = $values['extId'] ?? null;
        $this->id = $values['id'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
