<?php

namespace Brevo\CustomObjects\Types;

use Brevo\Core\Json\JsonSerializableType;
use Brevo\Core\Json\JsonProperty;
use Brevo\Core\Types\ArrayType;
use Brevo\Core\Types\Union;
use DateTime;
use Brevo\Core\Types\Date;

class GetrecordsResponseRecordsItem extends JsonSerializableType
{
    /**
     * @var ?array<(
     *    GetrecordsResponseRecordsItemAssociationsItemZero
     *   |GetrecordsResponseRecordsItemAssociationsItemOne
     * )> $associations List of associations for the object record. If association query param is true it will return 5 associated records per association.
     */
    #[JsonProperty('associations'), ArrayType([new Union(GetrecordsResponseRecordsItemAssociationsItemZero::class, GetrecordsResponseRecordsItemAssociationsItemOne::class)])]
    public ?array $associations;

    /**
     * @var ?array<string, mixed> $attributes Attributes attached with the object record. Only the already created attributes will be used with records. Minimum 1 attribute is required.
     */
    #[JsonProperty('attributes'), ArrayType(['string' => 'mixed'])]
    public ?array $attributes;

    /**
     * @var ?DateTime $createdAt Timestamp when the object record was created
     */
    #[JsonProperty('createdAt'), Date(Date::TYPE_DATETIME)]
    public ?DateTime $createdAt;

    /**
     * @var ?GetrecordsResponseRecordsItemIdentifiers $identifiers Identifiers attached with the object record. It can have id or ext_id. ext_id is ID of record in the external system that client want to store in the object system, id is an internal ID of object record generated by Brevo system.
     */
    #[JsonProperty('identifiers')]
    public ?GetrecordsResponseRecordsItemIdentifiers $identifiers;

    /**
     * @var ?DateTime $updatedAt Timestamp when the object record was last updated
     */
    #[JsonProperty('updatedAt'), Date(Date::TYPE_DATETIME)]
    public ?DateTime $updatedAt;

    /**
     * @param array{
     *   associations?: ?array<(
     *    GetrecordsResponseRecordsItemAssociationsItemZero
     *   |GetrecordsResponseRecordsItemAssociationsItemOne
     * )>,
     *   attributes?: ?array<string, mixed>,
     *   createdAt?: ?DateTime,
     *   identifiers?: ?GetrecordsResponseRecordsItemIdentifiers,
     *   updatedAt?: ?DateTime,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->associations = $values['associations'] ?? null;
        $this->attributes = $values['attributes'] ?? null;
        $this->createdAt = $values['createdAt'] ?? null;
        $this->identifiers = $values['identifiers'] ?? null;
        $this->updatedAt = $values['updatedAt'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
