<?php

namespace Brevo\CustomObjects\Types;

use Brevo\Core\Json\JsonSerializableType;
use Brevo\Core\Json\JsonProperty;

/**
 * Identifiers for the object record. Supports `id` (singular, not `ids`) or `ext_id`.
 * - `ext_id`: Your external system's identifier for this record.
 * - `id`: Internal Brevo record ID — can only be used for **updating** existing records, not for creation.
 * NOTE:
 * - This is an optional field. If no identifier is provided, Brevo auto-generates an internal ID that you can use for future operations.
 * - If both `ext_id` and `id` are provided, `id` takes precedence and the operation is treated as an update. It is recommended to provide only one identifier per record.
 */
class UpsertrecordsRequestRecordsItemIdentifiers extends JsonSerializableType
{
    /**
     * @var ?string $extId ext_id is ID of record in the external system that client wants to store in the object system.
     */
    #[JsonProperty('ext_id')]
    public ?string $extId;

    /**
     * @var ?int $id Internal ID of the object record generated by Brevo
     */
    #[JsonProperty('id')]
    public ?int $id;

    /**
     * @param array{
     *   extId?: ?string,
     *   id?: ?int,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->extId = $values['extId'] ?? null;
        $this->id = $values['id'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
