<?php

namespace Brevo\CustomObjects\Types;

use Brevo\Core\Json\JsonSerializableType;
use Brevo\Core\Json\JsonProperty;

/**
 * Identifiers attached with the associated object record. It can be ext_id or id. NOTE: - Either ext_id or id is required, if both are not provided, then error will be returned. - Both ext_id and id cannot be provided in the same request.
 */
class UpsertrecordsRequestRecordsItemAssociationsItemOneRecordsItemZeroIdentifiers extends JsonSerializableType
{
    /**
     * @var ?string $extId ext_id is ID of record in the external system that client_dev want to store in the object system.
     */
    #[JsonProperty('ext_id')]
    public ?string $extId;

    /**
     * @var ?int $id Internal ID of the object record generated by Brevo
     */
    #[JsonProperty('id')]
    public ?int $id;

    /**
     * @param array{
     *   extId?: ?string,
     *   id?: ?int,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->extId = $values['extId'] ?? null;
        $this->id = $values['id'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
