<?php

namespace Brevo\CustomObjects\Types;

use Brevo\Core\Json\JsonSerializableType;
use Brevo\Core\Json\JsonProperty;

/**
 * Identifiers for the associated object record. Provide either `ext_id` or `id`.
 */
class UpsertrecordsRequestRecordsItemAssociationsItemRecordsItemIdentifiers extends JsonSerializableType
{
    /**
     * @var ?string $extId External ID of the associated record in your system.
     */
    #[JsonProperty('ext_id')]
    public ?string $extId;

    /**
     * @var ?int $id Internal ID of the associated object record generated by Brevo.
     */
    #[JsonProperty('id')]
    public ?int $id;

    /**
     * @param array{
     *   extId?: ?string,
     *   id?: ?int,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->extId = $values['extId'] ?? null;
        $this->id = $values['id'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
