<?php
/**
 * ContactBalances
 *
 * PHP version 8.1
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brevo\Client\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Brevo\Client\ObjectSerializer;

/**
 * ContactBalances Class Doc Comment
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ContactBalances extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'contactBalances';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'loyaltyProgramId' => 'string',
        'balanceDefinitionId' => 'string',
        'count' => 'int',
        'balances' => '\Brevo\Client\Models\ContactBalancesBalancesInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'loyaltyProgramId' => 'uuid',
        'balanceDefinitionId' => 'uuid',
        'count' => null,
        'balances' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'loyaltyProgramId' => false,
        'balanceDefinitionId' => false,
        'count' => false,
        'balances' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'loyaltyProgramId' => 'loyaltyProgramId',
        'balanceDefinitionId' => 'balanceDefinitionId',
        'count' => 'count',
        'balances' => 'balances'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'loyaltyProgramId' => 'setLoyaltyProgramId',
        'balanceDefinitionId' => 'setBalanceDefinitionId',
        'count' => 'setCount',
        'balances' => 'setBalances'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'loyaltyProgramId' => 'getLoyaltyProgramId',
        'balanceDefinitionId' => 'getBalanceDefinitionId',
        'count' => 'getCount',
        'balances' => 'getBalances'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('loyaltyProgramId', $data ?? [], null);
        $this->setIfExists('balanceDefinitionId', $data ?? [], null);
        $this->setIfExists('count', $data ?? [], null);
        $this->setIfExists('balances', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['loyaltyProgramId'] === null) {
            $invalidProperties[] = "'loyaltyProgramId' can't be null";
        }
        if ($this->container['balanceDefinitionId'] === null) {
            $invalidProperties[] = "'balanceDefinitionId' can't be null";
        }
        if ($this->container['count'] === null) {
            $invalidProperties[] = "'count' can't be null";
        }
        if ($this->container['balances'] === null) {
            $invalidProperties[] = "'balances' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Gets loyaltyProgramId
     *
     * @return string
     */
    public function getLoyaltyProgramId(): string
    {
        return $this->container['loyaltyProgramId'];
    }

    /**
     * Sets loyaltyProgramId
     *
     * @param string $loyaltyProgramId Unique identifier for the loyalty program.
     *
     * @return $this
     */
    public function setLoyaltyProgramId(string $loyaltyProgramId): static
    {
        if (is_null($loyaltyProgramId)) {
            throw new InvalidArgumentException('non-nullable loyaltyProgramId cannot be null');
        }
        $this->container['loyaltyProgramId'] = $loyaltyProgramId;

        return $this;
    }

    /**
     * Gets balanceDefinitionId
     *
     * @return string
     */
    public function getBalanceDefinitionId(): string
    {
        return $this->container['balanceDefinitionId'];
    }

    /**
     * Sets balanceDefinitionId
     *
     * @param string $balanceDefinitionId Unique identifier for the balance definition.
     *
     * @return $this
     */
    public function setBalanceDefinitionId(string $balanceDefinitionId): static
    {
        if (is_null($balanceDefinitionId)) {
            throw new InvalidArgumentException('non-nullable balanceDefinitionId cannot be null');
        }
        $this->container['balanceDefinitionId'] = $balanceDefinitionId;

        return $this;
    }

    /**
     * Gets count
     *
     * @return int
     */
    public function getCount(): int
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param int $count Total count of balances.
     *
     * @return $this
     */
    public function setCount(int $count): static
    {
        if (is_null($count)) {
            throw new InvalidArgumentException('non-nullable count cannot be null');
        }
        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets balances
     *
     * @return \Brevo\Client\Models\ContactBalancesBalancesInner[]
     */
    public function getBalances(): array
    {
        return $this->container['balances'];
    }

    /**
     * Sets balances
     *
     * @param \Brevo\Client\Models\ContactBalancesBalancesInner[] $balances balances
     *
     * @return $this
     */
    public function setBalances(array $balances): static
    {
        if (is_null($balances)) {
            throw new InvalidArgumentException('non-nullable balances cannot be null');
        }
        $this->container['balances'] = $balances;

        return $this;
    }
}


