<?php
/**
 * ConversationsMessageFile
 *
 * PHP version 8.1
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brevo\Client\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Brevo\Client\ObjectSerializer;

/**
 * ConversationsMessageFile Class Doc Comment
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ConversationsMessageFile extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ConversationsMessage_file';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'filename' => 'string',
        'size' => 'int',
        'isImage' => 'bool',
        'url' => 'string',
        'imageInfo' => '\Brevo\Client\Models\ConversationsMessageFileImageInfo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'filename' => null,
        'size' => 'int64',
        'isImage' => null,
        'url' => 'url',
        'imageInfo' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'filename' => false,
        'size' => false,
        'isImage' => false,
        'url' => false,
        'imageInfo' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'filename' => 'filename',
        'size' => 'size',
        'isImage' => 'isImage',
        'url' => 'url',
        'imageInfo' => 'imageInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'filename' => 'setFilename',
        'size' => 'setSize',
        'isImage' => 'setIsImage',
        'url' => 'setUrl',
        'imageInfo' => 'setImageInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'filename' => 'getFilename',
        'size' => 'getSize',
        'isImage' => 'getIsImage',
        'url' => 'getUrl',
        'imageInfo' => 'getImageInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('filename', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
        $this->setIfExists('isImage', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('imageInfo', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['size']) && ($this->container['size'] < 0)) {
            $invalidProperties[] = "invalid value for 'size', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Gets filename
     *
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->container['filename'];
    }

    /**
     * Sets filename
     *
     * @param string|null $filename Name of the file
     *
     * @return $this
     */
    public function setFilename(?string $filename): static
    {
        if (is_null($filename)) {
            throw new InvalidArgumentException('non-nullable filename cannot be null');
        }
        $this->container['filename'] = $filename;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int|null
     */
    public function getSize(): ?int
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int|null $size Size in bytes
     *
     * @return $this
     */
    public function setSize(?int $size): static
    {
        if (is_null($size)) {
            throw new InvalidArgumentException('non-nullable size cannot be null');
        }

        if (($size < 0)) {
            throw new InvalidArgumentException('invalid value for $size when calling ConversationsMessageFile., must be bigger than or equal to 0.');
        }

        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets isImage
     *
     * @return bool|null
     */
    public function getIsImage(): ?bool
    {
        return $this->container['isImage'];
    }

    /**
     * Sets isImage
     *
     * @param bool|null $isImage Whether the file is an image
     *
     * @return $this
     */
    public function setIsImage(?bool $isImage): static
    {
        if (is_null($isImage)) {
            throw new InvalidArgumentException('non-nullable isImage cannot be null');
        }
        $this->container['isImage'] = $isImage;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl(): ?string
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url URL of the file
     *
     * @return $this
     */
    public function setUrl(?string $url): static
    {
        if (is_null($url)) {
            throw new InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets imageInfo
     *
     * @return \Brevo\Client\Models\ConversationsMessageFileImageInfo|null
     */
    public function getImageInfo(): ?\Brevo\Client\Models\ConversationsMessageFileImageInfo
    {
        return $this->container['imageInfo'];
    }

    /**
     * Sets imageInfo
     *
     * @param \Brevo\Client\Models\ConversationsMessageFileImageInfo|null $imageInfo imageInfo
     *
     * @return $this
     */
    public function setImageInfo(?\Brevo\Client\Models\ConversationsMessageFileImageInfo $imageInfo): static
    {
        if (is_null($imageInfo)) {
            throw new InvalidArgumentException('non-nullable imageInfo cannot be null');
        }
        $this->container['imageInfo'] = $imageInfo;

        return $this;
    }
}


