<?php
/**
 * GetExternalFeedByUUID
 *
 * PHP version 8.1
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brevo\Client\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Brevo\Client\ObjectSerializer;

/**
 * GetExternalFeedByUUID Class Doc Comment
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GetExternalFeedByUUID extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'getExternalFeedByUUID';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'url' => 'string',
        'authType' => 'string',
        'headers' => '\Brevo\Client\Models\GetExternalFeedByUUIDHeadersInner[]',
        'maxRetries' => 'int',
        'cache' => 'bool',
        'createdAt' => '\DateTime',
        'modifiedAt' => '\DateTime',
        'username' => 'string',
        'password' => 'string',
        'token' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => 'uuidv4',
        'name' => null,
        'url' => 'url',
        'authType' => null,
        'headers' => null,
        'maxRetries' => null,
        'cache' => null,
        'createdAt' => 'date-time',
        'modifiedAt' => 'date-time',
        'username' => null,
        'password' => null,
        'token' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'url' => false,
        'authType' => false,
        'headers' => false,
        'maxRetries' => false,
        'cache' => false,
        'createdAt' => false,
        'modifiedAt' => false,
        'username' => false,
        'password' => false,
        'token' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'url' => 'url',
        'authType' => 'authType',
        'headers' => 'headers',
        'maxRetries' => 'maxRetries',
        'cache' => 'cache',
        'createdAt' => 'createdAt',
        'modifiedAt' => 'modifiedAt',
        'username' => 'username',
        'password' => 'password',
        'token' => 'token'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'url' => 'setUrl',
        'authType' => 'setAuthType',
        'headers' => 'setHeaders',
        'maxRetries' => 'setMaxRetries',
        'cache' => 'setCache',
        'createdAt' => 'setCreatedAt',
        'modifiedAt' => 'setModifiedAt',
        'username' => 'setUsername',
        'password' => 'setPassword',
        'token' => 'setToken'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'url' => 'getUrl',
        'authType' => 'getAuthType',
        'headers' => 'getHeaders',
        'maxRetries' => 'getMaxRetries',
        'cache' => 'getCache',
        'createdAt' => 'getCreatedAt',
        'modifiedAt' => 'getModifiedAt',
        'username' => 'getUsername',
        'password' => 'getPassword',
        'token' => 'getToken'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    public const AUTH_TYPE_BASIC = 'basic';
    public const AUTH_TYPE_TOKEN = 'token';
    public const AUTH_TYPE_NO_AUTH = 'noAuth';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAuthTypeAllowableValues()
    {
        return [
            self::AUTH_TYPE_BASIC,
            self::AUTH_TYPE_TOKEN,
            self::AUTH_TYPE_NO_AUTH,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('authType', $data ?? [], null);
        $this->setIfExists('headers', $data ?? [], null);
        $this->setIfExists('maxRetries', $data ?? [], 5);
        $this->setIfExists('cache', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('modifiedAt', $data ?? [], null);
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('token', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['authType'] === null) {
            $invalidProperties[] = "'authType' can't be null";
        }
        $allowedValues = $this->getAuthTypeAllowableValues();
        if (!is_null($this->container['authType']) && !in_array($this->container['authType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'authType', must be one of '%s'",
                $this->container['authType'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['headers'] === null) {
            $invalidProperties[] = "'headers' can't be null";
        }
        if ($this->container['maxRetries'] === null) {
            $invalidProperties[] = "'maxRetries' can't be null";
        }
        if (($this->container['maxRetries'] > 5)) {
            $invalidProperties[] = "invalid value for 'maxRetries', must be smaller than or equal to 5.";
        }

        if (($this->container['maxRetries'] < 0)) {
            $invalidProperties[] = "invalid value for 'maxRetries', must be bigger than or equal to 0.";
        }

        if ($this->container['cache'] === null) {
            $invalidProperties[] = "'cache' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['modifiedAt'] === null) {
            $invalidProperties[] = "'modifiedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id ID of the feed
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Name of the feed
     *
     * @return $this
     */
    public function setName(string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl(): string
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url URL of the feed
     *
     * @return $this
     */
    public function setUrl(string $url): static
    {
        if (is_null($url)) {
            throw new InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets authType
     *
     * @return string
     */
    public function getAuthType(): string
    {
        return $this->container['authType'];
    }

    /**
     * Sets authType
     *
     * @param string $authType Auth type of the feed: * `basic` * `token` * `noAuth`
     *
     * @return $this
     */
    public function setAuthType(string $authType): static
    {
        if (is_null($authType)) {
            throw new InvalidArgumentException('non-nullable authType cannot be null');
        }
        $allowedValues = $this->getAuthTypeAllowableValues();
        if (!in_array($authType, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'authType', must be one of '%s'",
                    $authType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['authType'] = $authType;

        return $this;
    }

    /**
     * Gets headers
     *
     * @return \Brevo\Client\Models\GetExternalFeedByUUIDHeadersInner[]
     */
    public function getHeaders(): array
    {
        return $this->container['headers'];
    }

    /**
     * Sets headers
     *
     * @param \Brevo\Client\Models\GetExternalFeedByUUIDHeadersInner[] $headers Custom headers for the feed
     *
     * @return $this
     */
    public function setHeaders(array $headers): static
    {
        if (is_null($headers)) {
            throw new InvalidArgumentException('non-nullable headers cannot be null');
        }
        $this->container['headers'] = $headers;

        return $this;
    }

    /**
     * Gets maxRetries
     *
     * @return int
     */
    public function getMaxRetries(): int
    {
        return $this->container['maxRetries'];
    }

    /**
     * Sets maxRetries
     *
     * @param int $maxRetries Maximum number of retries on the feed url
     *
     * @return $this
     */
    public function setMaxRetries(int $maxRetries): static
    {
        if (is_null($maxRetries)) {
            throw new InvalidArgumentException('non-nullable maxRetries cannot be null');
        }

        if (($maxRetries > 5)) {
            throw new InvalidArgumentException('invalid value for $maxRetries when calling GetExternalFeedByUUID., must be smaller than or equal to 5.');
        }
        if (($maxRetries < 0)) {
            throw new InvalidArgumentException('invalid value for $maxRetries when calling GetExternalFeedByUUID., must be bigger than or equal to 0.');
        }

        $this->container['maxRetries'] = $maxRetries;

        return $this;
    }

    /**
     * Gets cache
     *
     * @return bool
     */
    public function getCache(): bool
    {
        return $this->container['cache'];
    }

    /**
     * Sets cache
     *
     * @param bool $cache Toggle caching of feed url response
     *
     * @return $this
     */
    public function setCache(bool $cache): static
    {
        if (is_null($cache)) {
            throw new InvalidArgumentException('non-nullable cache cannot be null');
        }
        $this->container['cache'] = $cache;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt Datetime on which the feed was created
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets modifiedAt
     *
     * @return \DateTime
     */
    public function getModifiedAt(): \DateTime
    {
        return $this->container['modifiedAt'];
    }

    /**
     * Sets modifiedAt
     *
     * @param \DateTime $modifiedAt Datetime on which the feed was modified
     *
     * @return $this
     */
    public function setModifiedAt(\DateTime $modifiedAt): static
    {
        if (is_null($modifiedAt)) {
            throw new InvalidArgumentException('non-nullable modifiedAt cannot be null');
        }
        $this->container['modifiedAt'] = $modifiedAt;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername(): ?string
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username Username for authType `basic`
     *
     * @return $this
     */
    public function setUsername(?string $username): static
    {
        if (is_null($username)) {
            throw new InvalidArgumentException('non-nullable username cannot be null');
        }
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string|null $password Password for authType `basic`
     *
     * @return $this
     */
    public function setPassword(?string $password): static
    {
        if (is_null($password)) {
            throw new InvalidArgumentException('non-nullable password cannot be null');
        }
        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets token
     *
     * @return string|null
     */
    public function getToken(): ?string
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string|null $token Token for authType `token`
     *
     * @return $this
     */
    public function setToken(?string $token): static
    {
        if (is_null($token)) {
            throw new InvalidArgumentException('non-nullable token cannot be null');
        }
        $this->container['token'] = $token;

        return $this;
    }
}


