<?php
/**
 * GetWhatsappCampaignOverview
 *
 * PHP version 8.1
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brevo\Client\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Brevo\Client\ObjectSerializer;

/**
 * GetWhatsappCampaignOverview Class Doc Comment
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GetWhatsappCampaignOverview extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'getWhatsappCampaignOverview';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'campaignName' => 'string',
        'campaignStatus' => 'string',
        'senderNumber' => 'string',
        'template' => '\Brevo\Client\Models\WhatsappCampTemplate',
        'createdAt' => 'string',
        'modifiedAt' => 'string',
        'scheduledAt' => 'string',
        'stats' => '\Brevo\Client\Models\WhatsappCampStats'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => 'int64',
        'campaignName' => null,
        'campaignStatus' => null,
        'senderNumber' => null,
        'template' => null,
        'createdAt' => null,
        'modifiedAt' => null,
        'scheduledAt' => null,
        'stats' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'campaignName' => false,
        'campaignStatus' => false,
        'senderNumber' => false,
        'template' => false,
        'createdAt' => false,
        'modifiedAt' => false,
        'scheduledAt' => false,
        'stats' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'campaignName' => 'campaignName',
        'campaignStatus' => 'campaignStatus',
        'senderNumber' => 'senderNumber',
        'template' => 'template',
        'createdAt' => 'createdAt',
        'modifiedAt' => 'modifiedAt',
        'scheduledAt' => 'scheduledAt',
        'stats' => 'stats'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'campaignName' => 'setCampaignName',
        'campaignStatus' => 'setCampaignStatus',
        'senderNumber' => 'setSenderNumber',
        'template' => 'setTemplate',
        'createdAt' => 'setCreatedAt',
        'modifiedAt' => 'setModifiedAt',
        'scheduledAt' => 'setScheduledAt',
        'stats' => 'setStats'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'campaignName' => 'getCampaignName',
        'campaignStatus' => 'getCampaignStatus',
        'senderNumber' => 'getSenderNumber',
        'template' => 'getTemplate',
        'createdAt' => 'getCreatedAt',
        'modifiedAt' => 'getModifiedAt',
        'scheduledAt' => 'getScheduledAt',
        'stats' => 'getStats'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    public const CAMPAIGN_STATUS_DRAFT = 'draft';
    public const CAMPAIGN_STATUS_SCHEDULED = 'scheduled';
    public const CAMPAIGN_STATUS_PENDING = 'pending';
    public const CAMPAIGN_STATUS_APPROVED = 'approved';
    public const CAMPAIGN_STATUS_RUNNING = 'running';
    public const CAMPAIGN_STATUS_SUSPENDED = 'suspended';
    public const CAMPAIGN_STATUS_REJECTED = 'rejected';
    public const CAMPAIGN_STATUS_SENT = 'sent';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCampaignStatusAllowableValues()
    {
        return [
            self::CAMPAIGN_STATUS_DRAFT,
            self::CAMPAIGN_STATUS_SCHEDULED,
            self::CAMPAIGN_STATUS_PENDING,
            self::CAMPAIGN_STATUS_APPROVED,
            self::CAMPAIGN_STATUS_RUNNING,
            self::CAMPAIGN_STATUS_SUSPENDED,
            self::CAMPAIGN_STATUS_REJECTED,
            self::CAMPAIGN_STATUS_SENT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('campaignName', $data ?? [], null);
        $this->setIfExists('campaignStatus', $data ?? [], null);
        $this->setIfExists('senderNumber', $data ?? [], null);
        $this->setIfExists('template', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('modifiedAt', $data ?? [], null);
        $this->setIfExists('scheduledAt', $data ?? [], null);
        $this->setIfExists('stats', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['campaignName'] === null) {
            $invalidProperties[] = "'campaignName' can't be null";
        }
        if ($this->container['campaignStatus'] === null) {
            $invalidProperties[] = "'campaignStatus' can't be null";
        }
        $allowedValues = $this->getCampaignStatusAllowableValues();
        if (!is_null($this->container['campaignStatus']) && !in_array($this->container['campaignStatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'campaignStatus', must be one of '%s'",
                $this->container['campaignStatus'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['senderNumber'] === null) {
            $invalidProperties[] = "'senderNumber' can't be null";
        }
        if ($this->container['template'] === null) {
            $invalidProperties[] = "'template' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['modifiedAt'] === null) {
            $invalidProperties[] = "'modifiedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId(): int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id ID of the WhatsApp Campaign
     *
     * @return $this
     */
    public function setId(int $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets campaignName
     *
     * @return string
     */
    public function getCampaignName(): string
    {
        return $this->container['campaignName'];
    }

    /**
     * Sets campaignName
     *
     * @param string $campaignName Name of the WhatsApp Campaign
     *
     * @return $this
     */
    public function setCampaignName(string $campaignName): static
    {
        if (is_null($campaignName)) {
            throw new InvalidArgumentException('non-nullable campaignName cannot be null');
        }
        $this->container['campaignName'] = $campaignName;

        return $this;
    }

    /**
     * Gets campaignStatus
     *
     * @return string
     */
    public function getCampaignStatus(): string
    {
        return $this->container['campaignStatus'];
    }

    /**
     * Sets campaignStatus
     *
     * @param string $campaignStatus Status of the WhatsApp Campaign
     *
     * @return $this
     */
    public function setCampaignStatus(string $campaignStatus): static
    {
        if (is_null($campaignStatus)) {
            throw new InvalidArgumentException('non-nullable campaignStatus cannot be null');
        }
        $allowedValues = $this->getCampaignStatusAllowableValues();
        if (!in_array($campaignStatus, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'campaignStatus', must be one of '%s'",
                    $campaignStatus,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['campaignStatus'] = $campaignStatus;

        return $this;
    }

    /**
     * Gets senderNumber
     *
     * @return string
     */
    public function getSenderNumber(): string
    {
        return $this->container['senderNumber'];
    }

    /**
     * Sets senderNumber
     *
     * @param string $senderNumber Sender of the WhatsApp Campaign
     *
     * @return $this
     */
    public function setSenderNumber(string $senderNumber): static
    {
        if (is_null($senderNumber)) {
            throw new InvalidArgumentException('non-nullable senderNumber cannot be null');
        }
        $this->container['senderNumber'] = $senderNumber;

        return $this;
    }

    /**
     * Gets template
     *
     * @return \Brevo\Client\Models\WhatsappCampTemplate
     */
    public function getTemplate(): \Brevo\Client\Models\WhatsappCampTemplate
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     *
     * @param \Brevo\Client\Models\WhatsappCampTemplate $template template
     *
     * @return $this
     */
    public function setTemplate(\Brevo\Client\Models\WhatsappCampTemplate $template): static
    {
        if (is_null($template)) {
            throw new InvalidArgumentException('non-nullable template cannot be null');
        }
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return string
     */
    public function getCreatedAt(): string
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param string $createdAt Creation UTC date-time of the WhatsApp campaign (YYYY-MM-DDTHH:mm:ss.SSSZ)
     *
     * @return $this
     */
    public function setCreatedAt(string $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets modifiedAt
     *
     * @return string
     */
    public function getModifiedAt(): string
    {
        return $this->container['modifiedAt'];
    }

    /**
     * Sets modifiedAt
     *
     * @param string $modifiedAt UTC date-time of last modification of the WhatsApp campaign (YYYY-MM-DDTHH:mm:ss.SSSZ)
     *
     * @return $this
     */
    public function setModifiedAt(string $modifiedAt): static
    {
        if (is_null($modifiedAt)) {
            throw new InvalidArgumentException('non-nullable modifiedAt cannot be null');
        }
        $this->container['modifiedAt'] = $modifiedAt;

        return $this;
    }

    /**
     * Gets scheduledAt
     *
     * @return string|null
     */
    public function getScheduledAt(): ?string
    {
        return $this->container['scheduledAt'];
    }

    /**
     * Sets scheduledAt
     *
     * @param string|null $scheduledAt UTC date-time on which WhatsApp campaign is scheduled. Should be in YYYY-MM-DDTHH:mm:ss.SSSZ format
     *
     * @return $this
     */
    public function setScheduledAt(?string $scheduledAt): static
    {
        if (is_null($scheduledAt)) {
            throw new InvalidArgumentException('non-nullable scheduledAt cannot be null');
        }
        $this->container['scheduledAt'] = $scheduledAt;

        return $this;
    }

    /**
     * Gets stats
     *
     * @return \Brevo\Client\Models\WhatsappCampStats|null
     */
    public function getStats(): ?\Brevo\Client\Models\WhatsappCampStats
    {
        return $this->container['stats'];
    }

    /**
     * Sets stats
     *
     * @param \Brevo\Client\Models\WhatsappCampStats|null $stats stats
     *
     * @return $this
     */
    public function setStats(?\Brevo\Client\Models\WhatsappCampStats $stats): static
    {
        if (is_null($stats)) {
            throw new InvalidArgumentException('non-nullable stats cannot be null');
        }
        $this->container['stats'] = $stats;

        return $this;
    }
}


