<?php
/**
 * MasterDetailsResponse
 *
 * PHP version 8.1
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brevo\Client\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Brevo\Client\ObjectSerializer;

/**
 * MasterDetailsResponse Class Doc Comment
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MasterDetailsResponse extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'masterDetailsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'email' => 'string',
        'companyName' => 'string',
        'id' => 'int',
        'currencyCode' => 'string',
        'timezone' => 'string',
        'billingInfo' => '\Brevo\Client\Models\MasterDetailsResponseBillingInfo',
        'planInfo' => '\Brevo\Client\Models\MasterDetailsResponsePlanInfo'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'email' => null,
        'companyName' => null,
        'id' => 'int64',
        'currencyCode' => null,
        'timezone' => null,
        'billingInfo' => null,
        'planInfo' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'email' => false,
        'companyName' => false,
        'id' => false,
        'currencyCode' => false,
        'timezone' => false,
        'billingInfo' => false,
        'planInfo' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'email' => 'email',
        'companyName' => 'companyName',
        'id' => 'id',
        'currencyCode' => 'currencyCode',
        'timezone' => 'timezone',
        'billingInfo' => 'billingInfo',
        'planInfo' => 'planInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'email' => 'setEmail',
        'companyName' => 'setCompanyName',
        'id' => 'setId',
        'currencyCode' => 'setCurrencyCode',
        'timezone' => 'setTimezone',
        'billingInfo' => 'setBillingInfo',
        'planInfo' => 'setPlanInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'email' => 'getEmail',
        'companyName' => 'getCompanyName',
        'id' => 'getId',
        'currencyCode' => 'getCurrencyCode',
        'timezone' => 'getTimezone',
        'billingInfo' => 'getBillingInfo',
        'planInfo' => 'getPlanInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('companyName', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('currencyCode', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
        $this->setIfExists('billingInfo', $data ?? [], null);
        $this->setIfExists('planInfo', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Email id of master account
     *
     * @return $this
     */
    public function setEmail(?string $email): static
    {
        if (is_null($email)) {
            throw new InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets companyName
     *
     * @return string|null
     */
    public function getCompanyName(): ?string
    {
        return $this->container['companyName'];
    }

    /**
     * Sets companyName
     *
     * @param string|null $companyName Company name of master account organization
     *
     * @return $this
     */
    public function setCompanyName(?string $companyName): static
    {
        if (is_null($companyName)) {
            throw new InvalidArgumentException('non-nullable companyName cannot be null');
        }
        $this->container['companyName'] = $companyName;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id Unique identifier of the master account organization
     *
     * @return $this
     */
    public function setId(?int $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets currencyCode
     *
     * @return string|null
     */
    public function getCurrencyCode(): ?string
    {
        return $this->container['currencyCode'];
    }

    /**
     * Sets currencyCode
     *
     * @param string|null $currencyCode Currency code of the master account organization
     *
     * @return $this
     */
    public function setCurrencyCode(?string $currencyCode): static
    {
        if (is_null($currencyCode)) {
            throw new InvalidArgumentException('non-nullable currencyCode cannot be null');
        }
        $this->container['currencyCode'] = $currencyCode;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string|null
     */
    public function getTimezone(): ?string
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string|null $timezone Timezone of the master account organization
     *
     * @return $this
     */
    public function setTimezone(?string $timezone): static
    {
        if (is_null($timezone)) {
            throw new InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets billingInfo
     *
     * @return \Brevo\Client\Models\MasterDetailsResponseBillingInfo|null
     */
    public function getBillingInfo(): ?\Brevo\Client\Models\MasterDetailsResponseBillingInfo
    {
        return $this->container['billingInfo'];
    }

    /**
     * Sets billingInfo
     *
     * @param \Brevo\Client\Models\MasterDetailsResponseBillingInfo|null $billingInfo billingInfo
     *
     * @return $this
     */
    public function setBillingInfo(?\Brevo\Client\Models\MasterDetailsResponseBillingInfo $billingInfo): static
    {
        if (is_null($billingInfo)) {
            throw new InvalidArgumentException('non-nullable billingInfo cannot be null');
        }
        $this->container['billingInfo'] = $billingInfo;

        return $this;
    }

    /**
     * Gets planInfo
     *
     * @return \Brevo\Client\Models\MasterDetailsResponsePlanInfo|null
     */
    public function getPlanInfo(): ?\Brevo\Client\Models\MasterDetailsResponsePlanInfo
    {
        return $this->container['planInfo'];
    }

    /**
     * Sets planInfo
     *
     * @param \Brevo\Client\Models\MasterDetailsResponsePlanInfo|null $planInfo planInfo
     *
     * @return $this
     */
    public function setPlanInfo(?\Brevo\Client\Models\MasterDetailsResponsePlanInfo $planInfo): static
    {
        if (is_null($planInfo)) {
            throw new InvalidArgumentException('non-nullable planInfo cannot be null');
        }
        $this->container['planInfo'] = $planInfo;

        return $this;
    }
}


