<?php
/**
 * Pipeline
 *
 * PHP version 8.1
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brevo\Client\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Brevo\Client\ObjectSerializer;

/**
 * Pipeline Class Doc Comment
 *
 * @description List of stages
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class Pipeline extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'Pipeline';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'pipelineName' => 'string',
        'pipeline' => 'string',
        'stages' => '\Brevo\Client\Models\PipelineStage[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'pipelineName' => null,
        'pipeline' => null,
        'stages' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'pipelineName' => false,
        'pipeline' => false,
        'stages' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'pipelineName' => 'pipeline_name',
        'pipeline' => 'pipeline',
        'stages' => 'stages'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'pipelineName' => 'setPipelineName',
        'pipeline' => 'setPipeline',
        'stages' => 'setStages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'pipelineName' => 'getPipelineName',
        'pipeline' => 'getPipeline',
        'stages' => 'getStages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('pipelineName', $data ?? [], null);
        $this->setIfExists('pipeline', $data ?? [], null);
        $this->setIfExists('stages', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Gets pipelineName
     *
     * @return string|null
     */
    public function getPipelineName(): ?string
    {
        return $this->container['pipelineName'];
    }

    /**
     * Sets pipelineName
     *
     * @param string|null $pipelineName Pipeline name
     *
     * @return $this
     */
    public function setPipelineName(?string $pipelineName): static
    {
        if (is_null($pipelineName)) {
            throw new InvalidArgumentException('non-nullable pipelineName cannot be null');
        }
        $this->container['pipelineName'] = $pipelineName;

        return $this;
    }

    /**
     * Gets pipeline
     *
     * @return string|null
     */
    public function getPipeline(): ?string
    {
        return $this->container['pipeline'];
    }

    /**
     * Sets pipeline
     *
     * @param string|null $pipeline Pipeline id
     *
     * @return $this
     */
    public function setPipeline(?string $pipeline): static
    {
        if (is_null($pipeline)) {
            throw new InvalidArgumentException('non-nullable pipeline cannot be null');
        }
        $this->container['pipeline'] = $pipeline;

        return $this;
    }

    /**
     * Gets stages
     *
     * @return \Brevo\Client\Models\PipelineStage[]|null
     */
    public function getStages(): ?array
    {
        return $this->container['stages'];
    }

    /**
     * Sets stages
     *
     * @param \Brevo\Client\Models\PipelineStage[]|null $stages List of stages
     *
     * @return $this
     */
    public function setStages(?array $stages): static
    {
        if (is_null($stages)) {
            throw new InvalidArgumentException('non-nullable stages cannot be null');
        }
        $this->container['stages'] = $stages;

        return $this;
    }
}


