<?php
/**
 * PostContactInfoContacts
 *
 * PHP version 8.1
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brevo\Client\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Brevo\Client\ObjectSerializer;

/**
 * PostContactInfoContacts Class Doc Comment
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class PostContactInfoContacts extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'postContactInfo_contacts';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'success' => '\Brevo\Client\Models\PostContactInfoContactsSuccess',
        'failure' => '\Brevo\Client\Models\PostContactInfoContactsFailure',
        'total' => 'int',
        'processId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'success' => null,
        'failure' => null,
        'total' => 'int64',
        'processId' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'success' => false,
        'failure' => false,
        'total' => false,
        'processId' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'success' => 'success',
        'failure' => 'failure',
        'total' => 'total',
        'processId' => 'processId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'success' => 'setSuccess',
        'failure' => 'setFailure',
        'total' => 'setTotal',
        'processId' => 'setProcessId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'success' => 'getSuccess',
        'failure' => 'getFailure',
        'total' => 'getTotal',
        'processId' => 'getProcessId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('success', $data ?? [], null);
        $this->setIfExists('failure', $data ?? [], null);
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('processId', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Gets success
     *
     * @return \Brevo\Client\Models\PostContactInfoContactsSuccess|null
     */
    public function getSuccess(): ?\Brevo\Client\Models\PostContactInfoContactsSuccess
    {
        return $this->container['success'];
    }

    /**
     * Sets success
     *
     * @param \Brevo\Client\Models\PostContactInfoContactsSuccess|null $success success
     *
     * @return $this
     */
    public function setSuccess(?\Brevo\Client\Models\PostContactInfoContactsSuccess $success): static
    {
        if (is_null($success)) {
            throw new InvalidArgumentException('non-nullable success cannot be null');
        }
        $this->container['success'] = $success;

        return $this;
    }

    /**
     * Gets failure
     *
     * @return \Brevo\Client\Models\PostContactInfoContactsFailure|null
     */
    public function getFailure(): ?\Brevo\Client\Models\PostContactInfoContactsFailure
    {
        return $this->container['failure'];
    }

    /**
     * Sets failure
     *
     * @param \Brevo\Client\Models\PostContactInfoContactsFailure|null $failure failure
     *
     * @return $this
     */
    public function setFailure(?\Brevo\Client\Models\PostContactInfoContactsFailure $failure): static
    {
        if (is_null($failure)) {
            throw new InvalidArgumentException('non-nullable failure cannot be null');
        }
        $this->container['failure'] = $failure;

        return $this;
    }

    /**
     * Gets total
     *
     * @return int|null
     */
    public function getTotal(): ?int
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param int|null $total Displays the count of total number of contacts removed from list when user opts for \"all\" option.
     *
     * @return $this
     */
    public function setTotal(?int $total): static
    {
        if (is_null($total)) {
            throw new InvalidArgumentException('non-nullable total cannot be null');
        }
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets processId
     *
     * @return int|null
     */
    public function getProcessId(): ?int
    {
        return $this->container['processId'];
    }

    /**
     * Sets processId
     *
     * @param int|null $processId Id of the process created to remove contacts from list when user opts for \"all\" option.
     *
     * @return $this
     */
    public function setProcessId(?int $processId): static
    {
        if (is_null($processId)) {
            throw new InvalidArgumentException('non-nullable processId cannot be null');
        }
        $this->container['processId'] = $processId;

        return $this;
    }
}


