<?php
/**
 * ValidateRewardPayload
 *
 * PHP version 8.1
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brevo\Client\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Brevo\Client\ObjectSerializer;

/**
 * ValidateRewardPayload Class Doc Comment
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ValidateRewardPayload extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'validateRewardPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'contactId' => 'float',
        'loyaltySubscriptionId' => 'string',
        'code' => 'string',
        'attributedRewardId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'contactId' => null,
        'loyaltySubscriptionId' => null,
        'code' => null,
        'attributedRewardId' => 'uuid'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'contactId' => false,
        'loyaltySubscriptionId' => false,
        'code' => false,
        'attributedRewardId' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'contactId' => 'contactId',
        'loyaltySubscriptionId' => 'loyaltySubscriptionId',
        'code' => 'code',
        'attributedRewardId' => 'attributedRewardId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'contactId' => 'setContactId',
        'loyaltySubscriptionId' => 'setLoyaltySubscriptionId',
        'code' => 'setCode',
        'attributedRewardId' => 'setAttributedRewardId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'contactId' => 'getContactId',
        'loyaltySubscriptionId' => 'getLoyaltySubscriptionId',
        'code' => 'getCode',
        'attributedRewardId' => 'getAttributedRewardId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('contactId', $data ?? [], null);
        $this->setIfExists('loyaltySubscriptionId', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('attributedRewardId', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Gets contactId
     *
     * @return float|null
     */
    public function getContactId(): ?float
    {
        return $this->container['contactId'];
    }

    /**
     * Sets contactId
     *
     * @param float|null $contactId Contact to attribute the reward
     *
     * @return $this
     */
    public function setContactId(?float $contactId): static
    {
        if (is_null($contactId)) {
            throw new InvalidArgumentException('non-nullable contactId cannot be null');
        }
        $this->container['contactId'] = $contactId;

        return $this;
    }

    /**
     * Gets loyaltySubscriptionId
     *
     * @return string|null
     */
    public function getLoyaltySubscriptionId(): ?string
    {
        return $this->container['loyaltySubscriptionId'];
    }

    /**
     * Sets loyaltySubscriptionId
     *
     * @param string|null $loyaltySubscriptionId One of contactId or loyaltySubscriptionId is required
     *
     * @return $this
     */
    public function setLoyaltySubscriptionId(?string $loyaltySubscriptionId): static
    {
        if (is_null($loyaltySubscriptionId)) {
            throw new InvalidArgumentException('non-nullable loyaltySubscriptionId cannot be null');
        }
        $this->container['loyaltySubscriptionId'] = $loyaltySubscriptionId;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode(): ?string
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code Code to validate
     *
     * @return $this
     */
    public function setCode(?string $code): static
    {
        if (is_null($code)) {
            throw new InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets attributedRewardId
     *
     * @return string|null
     */
    public function getAttributedRewardId(): ?string
    {
        return $this->container['attributedRewardId'];
    }

    /**
     * Sets attributedRewardId
     *
     * @param string|null $attributedRewardId One of code or attributed reward id is required
     *
     * @return $this
     */
    public function setAttributedRewardId(?string $attributedRewardId): static
    {
        if (is_null($attributedRewardId)) {
            throw new InvalidArgumentException('non-nullable attributedRewardId cannot be null');
        }
        $this->container['attributedRewardId'] = $attributedRewardId;

        return $this;
    }
}


