<?php
/**
 * VersionInfo
 *
 * PHP version 8.1
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@brevo.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Brevo\Client\Models;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Brevo\Client\ObjectSerializer;

/**
 * VersionInfo Class Doc Comment
 *
 * @package  Brevo\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class VersionInfo extends AbstractModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'versionInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'name' => 'string',
        'loyaltyProgramId' => 'string',
        'loyaltyVersionId' => 'int',
        'parentVersionId' => 'int',
        'state' => 'string',
        'publishedAt' => '\DateTime',
        'createdAt' => '\DateTime',
        'updatedAt' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'name' => null,
        'loyaltyProgramId' => 'uuid',
        'loyaltyVersionId' => null,
        'parentVersionId' => null,
        'state' => null,
        'publishedAt' => 'date-time',
        'createdAt' => 'date-time',
        'updatedAt' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'name' => false,
        'loyaltyProgramId' => false,
        'loyaltyVersionId' => false,
        'parentVersionId' => false,
        'state' => false,
        'publishedAt' => false,
        'createdAt' => false,
        'updatedAt' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'name' => 'name',
        'loyaltyProgramId' => 'loyaltyProgramId',
        'loyaltyVersionId' => 'loyaltyVersionId',
        'parentVersionId' => 'parentVersionId',
        'state' => 'state',
        'publishedAt' => 'publishedAt',
        'createdAt' => 'createdAt',
        'updatedAt' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'name' => 'setName',
        'loyaltyProgramId' => 'setLoyaltyProgramId',
        'loyaltyVersionId' => 'setLoyaltyVersionId',
        'parentVersionId' => 'setParentVersionId',
        'state' => 'setState',
        'publishedAt' => 'setPublishedAt',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'name' => 'getName',
        'loyaltyProgramId' => 'getLoyaltyProgramId',
        'loyaltyVersionId' => 'getLoyaltyVersionId',
        'parentVersionId' => 'getParentVersionId',
        'state' => 'getState',
        'publishedAt' => 'getPublishedAt',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('loyaltyProgramId', $data ?? [], null);
        $this->setIfExists('loyaltyVersionId', $data ?? [], null);
        $this->setIfExists('parentVersionId', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('publishedAt', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Version Name
     *
     * @return $this
     */
    public function setName(?string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets loyaltyProgramId
     *
     * @return string|null
     */
    public function getLoyaltyProgramId(): ?string
    {
        return $this->container['loyaltyProgramId'];
    }

    /**
     * Sets loyaltyProgramId
     *
     * @param string|null $loyaltyProgramId Loyalty Program Id
     *
     * @return $this
     */
    public function setLoyaltyProgramId(?string $loyaltyProgramId): static
    {
        if (is_null($loyaltyProgramId)) {
            throw new InvalidArgumentException('non-nullable loyaltyProgramId cannot be null');
        }
        $this->container['loyaltyProgramId'] = $loyaltyProgramId;

        return $this;
    }

    /**
     * Gets loyaltyVersionId
     *
     * @return int|null
     */
    public function getLoyaltyVersionId(): ?int
    {
        return $this->container['loyaltyVersionId'];
    }

    /**
     * Sets loyaltyVersionId
     *
     * @param int|null $loyaltyVersionId Loyalty Version Id
     *
     * @return $this
     */
    public function setLoyaltyVersionId(?int $loyaltyVersionId): static
    {
        if (is_null($loyaltyVersionId)) {
            throw new InvalidArgumentException('non-nullable loyaltyVersionId cannot be null');
        }
        $this->container['loyaltyVersionId'] = $loyaltyVersionId;

        return $this;
    }

    /**
     * Gets parentVersionId
     *
     * @return int|null
     */
    public function getParentVersionId(): ?int
    {
        return $this->container['parentVersionId'];
    }

    /**
     * Sets parentVersionId
     *
     * @param int|null $parentVersionId Parent Version Id
     *
     * @return $this
     */
    public function setParentVersionId(?int $parentVersionId): static
    {
        if (is_null($parentVersionId)) {
            throw new InvalidArgumentException('non-nullable parentVersionId cannot be null');
        }
        $this->container['parentVersionId'] = $parentVersionId;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState(): ?string
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state Version State
     *
     * @return $this
     */
    public function setState(?string $state): static
    {
        if (is_null($state)) {
            throw new InvalidArgumentException('non-nullable state cannot be null');
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets publishedAt
     *
     * @return \DateTime|null
     */
    public function getPublishedAt(): ?\DateTime
    {
        return $this->container['publishedAt'];
    }

    /**
     * Sets publishedAt
     *
     * @param \DateTime|null $publishedAt Version Publish date
     *
     * @return $this
     */
    public function setPublishedAt(?\DateTime $publishedAt): static
    {
        if (is_null($publishedAt)) {
            throw new InvalidArgumentException('non-nullable publishedAt cannot be null');
        }
        $this->container['publishedAt'] = $publishedAt;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime|null
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime|null $createdAt Version creation date
     *
     * @return $this
     */
    public function setCreatedAt(?\DateTime $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime|null $updatedAt Version last modification date
     *
     * @return $this
     */
    public function setUpdatedAt(?\DateTime $updatedAt): static
    {
        if (is_null($updatedAt)) {
            throw new InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
}


