<?php
/**
 * EventIdentifiers
 *
 * PHP version 5
 *
 * @category Class
 * @package  Brevo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Brevo API
 *
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity |
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Brevo\Client\Model;

use \ArrayAccess;
use \Brevo\Client\ObjectSerializer;

/**
 * EventIdentifiers Class Doc Comment
 *
 * @category Class
 * @description Identifies the contact associated with the event. At least one identifier is required.
 * @package  Brevo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EventIdentifiers implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'event_identifiers';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'emailId' => 'string',
        'phoneId' => 'string',
        'whatsappId' => 'string',
        'landlineNumberId' => 'string',
        'extId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'emailId' => null,
        'phoneId' => null,
        'whatsappId' => null,
        'landlineNumberId' => null,
        'extId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'emailId' => 'email_id',
        'phoneId' => 'phone_id',
        'whatsappId' => 'whatsapp_id',
        'landlineNumberId' => 'landline_number_id',
        'extId' => 'ext_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'emailId' => 'setEmailId',
        'phoneId' => 'setPhoneId',
        'whatsappId' => 'setWhatsappId',
        'landlineNumberId' => 'setLandlineNumberId',
        'extId' => 'setExtId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'emailId' => 'getEmailId',
        'phoneId' => 'getPhoneId',
        'whatsappId' => 'getWhatsappId',
        'landlineNumberId' => 'getLandlineNumberId',
        'extId' => 'getExtId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['emailId'] = isset($data['emailId']) ? $data['emailId'] : null;
        $this->container['phoneId'] = isset($data['phoneId']) ? $data['phoneId'] : null;
        $this->container['whatsappId'] = isset($data['whatsappId']) ? $data['whatsappId'] : null;
        $this->container['landlineNumberId'] = isset($data['landlineNumberId']) ? $data['landlineNumberId'] : null;
        $this->container['extId'] = isset($data['extId']) ? $data['extId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets emailId
     *
     * @return string
     */
    public function getEmailId()
    {
        return $this->container['emailId'];
    }

    /**
     * Sets emailId
     *
     * @param string $emailId Email Id associated with the event
     *
     * @return $this
     */
    public function setEmailId($emailId)
    {
        $this->container['emailId'] = $emailId;

        return $this;
    }

    /**
     * Gets phoneId
     *
     * @return string
     */
    public function getPhoneId()
    {
        return $this->container['phoneId'];
    }

    /**
     * Sets phoneId
     *
     * @param string $phoneId SMS associated with the event
     *
     * @return $this
     */
    public function setPhoneId($phoneId)
    {
        $this->container['phoneId'] = $phoneId;

        return $this;
    }

    /**
     * Gets whatsappId
     *
     * @return string
     */
    public function getWhatsappId()
    {
        return $this->container['whatsappId'];
    }

    /**
     * Sets whatsappId
     *
     * @param string $whatsappId whatsapp associated with the event
     *
     * @return $this
     */
    public function setWhatsappId($whatsappId)
    {
        $this->container['whatsappId'] = $whatsappId;

        return $this;
    }

    /**
     * Gets landlineNumberId
     *
     * @return string
     */
    public function getLandlineNumberId()
    {
        return $this->container['landlineNumberId'];
    }

    /**
     * Sets landlineNumberId
     *
     * @param string $landlineNumberId landline_number associated with the event
     *
     * @return $this
     */
    public function setLandlineNumberId($landlineNumberId)
    {
        $this->container['landlineNumberId'] = $landlineNumberId;

        return $this;
    }

    /**
     * Gets extId
     *
     * @return string
     */
    public function getExtId()
    {
        return $this->container['extId'];
    }

    /**
     * Sets extId
     *
     * @param string $extId ext_id associated with the event
     *
     * @return $this
     */
    public function setExtId($extId)
    {
        $this->container['extId'] = $extId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


