<?php

namespace Brevo\Contacts\Types;

use Brevo\Core\Json\JsonSerializableType;
use Brevo\Core\Json\JsonProperty;
use Brevo\Core\Types\ArrayType;

/**
 * Campaign statistics of the contact
 */
class GetContactInfoResponseStatistics extends JsonSerializableType
{
    /**
     * @var ?array<GetContactInfoResponseStatisticsClickedItem> $clicked Listing of the clicks generated by the contact
     */
    #[JsonProperty('clicked'), ArrayType([GetContactInfoResponseStatisticsClickedItem::class])]
    public ?array $clicked;

    /**
     * @var ?array<GetContactInfoResponseStatisticsComplaintsItem> $complaints Listing of the complaints generated by the contact
     */
    #[JsonProperty('complaints'), ArrayType([GetContactInfoResponseStatisticsComplaintsItem::class])]
    public ?array $complaints;

    /**
     * @var ?array<GetContactInfoResponseStatisticsDeliveredItem> $delivered Listing of the delivered campaign for the contact
     */
    #[JsonProperty('delivered'), ArrayType([GetContactInfoResponseStatisticsDeliveredItem::class])]
    public ?array $delivered;

    /**
     * @var ?array<GetContactInfoResponseStatisticsHardBouncesItem> $hardBounces Listing of the hardbounes generated by the contact
     */
    #[JsonProperty('hardBounces'), ArrayType([GetContactInfoResponseStatisticsHardBouncesItem::class])]
    public ?array $hardBounces;

    /**
     * @var ?array<GetContactInfoResponseStatisticsMessagesSentItem> $messagesSent Listing of the sent campaign for the contact
     */
    #[JsonProperty('messagesSent'), ArrayType([GetContactInfoResponseStatisticsMessagesSentItem::class])]
    public ?array $messagesSent;

    /**
     * @var ?array<GetContactInfoResponseStatisticsOpenedItem> $opened Listing of the openings generated by the contact
     */
    #[JsonProperty('opened'), ArrayType([GetContactInfoResponseStatisticsOpenedItem::class])]
    public ?array $opened;

    /**
     * @var ?array<GetContactInfoResponseStatisticsSoftBouncesItem> $softBounces Listing of the softbounes generated by the contact
     */
    #[JsonProperty('softBounces'), ArrayType([GetContactInfoResponseStatisticsSoftBouncesItem::class])]
    public ?array $softBounces;

    /**
     * @var ?array<GetContactInfoResponseStatisticsTransacAttributesItem> $transacAttributes Listing of the transactional attributes for the contact
     */
    #[JsonProperty('transacAttributes'), ArrayType([GetContactInfoResponseStatisticsTransacAttributesItem::class])]
    public ?array $transacAttributes;

    /**
     * @var ?GetContactInfoResponseStatisticsUnsubscriptions $unsubscriptions Listing of the unsubscription for the contact
     */
    #[JsonProperty('unsubscriptions')]
    public ?GetContactInfoResponseStatisticsUnsubscriptions $unsubscriptions;

    /**
     * @param array{
     *   clicked?: ?array<GetContactInfoResponseStatisticsClickedItem>,
     *   complaints?: ?array<GetContactInfoResponseStatisticsComplaintsItem>,
     *   delivered?: ?array<GetContactInfoResponseStatisticsDeliveredItem>,
     *   hardBounces?: ?array<GetContactInfoResponseStatisticsHardBouncesItem>,
     *   messagesSent?: ?array<GetContactInfoResponseStatisticsMessagesSentItem>,
     *   opened?: ?array<GetContactInfoResponseStatisticsOpenedItem>,
     *   softBounces?: ?array<GetContactInfoResponseStatisticsSoftBouncesItem>,
     *   transacAttributes?: ?array<GetContactInfoResponseStatisticsTransacAttributesItem>,
     *   unsubscriptions?: ?GetContactInfoResponseStatisticsUnsubscriptions,
     * } $values
     */
    public function __construct(
        array $values = [],
    ) {
        $this->clicked = $values['clicked'] ?? null;
        $this->complaints = $values['complaints'] ?? null;
        $this->delivered = $values['delivered'] ?? null;
        $this->hardBounces = $values['hardBounces'] ?? null;
        $this->messagesSent = $values['messagesSent'] ?? null;
        $this->opened = $values['opened'] ?? null;
        $this->softBounces = $values['softBounces'] ?? null;
        $this->transacAttributes = $values['transacAttributes'] ?? null;
        $this->unsubscriptions = $values['unsubscriptions'] ?? null;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
